name: On push workflow

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:

jobs:
  unit_test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          version: 10.27.0
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Run unit tests
        run: |
          pnpm install --frozen-lockfile
          pnpm test

  format_check:
    name: Biome format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          version: 10.27.0
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Run Biome format checks
        run: |
          pnpm install --frozen-lockfile
          pnpm format

  lint_check:
    name: Biome lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          version: 10.27.0
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Run Biome lint checks
        run: |
          pnpm install --frozen-lockfile
          pnpm lint
